# Generated by Django 4.1 on 2022-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockname", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="myimage")),
                ("title", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=250)),
            ],
        ),
    ]
