# Generated by Django 4.1 on 2022-10-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock", old_name="detail", new_name="description",
        ),
        migrations.RemoveField(model_name="stock", name="title",),
    ]
