# Generated by Django 4.1 on 2022-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_detail_stock_description_remove_stock_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("stockname", models.CharField(max_length=100)),
                ("question", models.TextField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(name="stock",),
    ]
