# Generated by Django 4.1 on 2022-10-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_query_delete_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="query", old_name="question", new_name="query",
        ),
    ]
