# Generated by Django 4.1 on 2022-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_question_query_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockname", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="myimage")),
                ("description", models.TextField(max_length=400)),
            ],
        ),
    ]
