# Generated by Django 4.1 on 2022-10-16 05:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_stock_dslug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="dslug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="description",
                unique=True,
            ),
        ),
    ]
